"""add subcategories table

Revision ID: 9c6920cb0ae6
Revises: d86de4abbf3e
Create Date: 2026-08-30 20:26:00.648643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6920cb0ae6'
down_revision: Union[str, Sequence[str], None] = 'd86de4abbf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'subcategories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('category_id', 'name'),
    )
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_index(op.f('ix_subcategories_id'), 'subcategories', ['id'], unique=False)

    # Синхронизируем таблицу с уже существующими метками товаров: каждая метка
    # подкатегории, встречающаяся у товаров, становится активной записью.
    # Пометка «Прямая»/«Угловая» для кухни гарантируется даже без товаров.
    connection = op.get_bind()
    categories = connection.execute(
        sa.text("SELECT id, name FROM categories")
    ).fetchall()
    for category_id, category_name in categories:
        labels = [
            row[0]
            for row in connection.execute(
                sa.text(
                    "SELECT DISTINCT subcategory FROM furniture "
                    "WHERE category_name = :name AND subcategory IS NOT NULL"
                ),
                {"name": category_name},
            ).fetchall()
        ]
        if category_name == "Кухонная мебель":
            for value in ("Прямая", "Угловая"):
                if value not in labels:
                    labels.append(value)
        for value in labels:
            exists = connection.execute(
                sa.text(
                    "SELECT 1 FROM subcategories "
                    "WHERE category_id = :cid AND name = :name"
                ),
                {"cid": category_id, "name": value},
            ).first()
            if not exists:
                connection.execute(
                    sa.text(
                        "INSERT INTO subcategories (category_id, name, is_deleted, created_at) "
                        "VALUES (:cid, :name, 0, CURRENT_TIMESTAMP)"
                    ),
                    {"cid": category_id, "name": value},
                )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcategories_id'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
